### ISSUE TITLE
May I study your paper related to the program?

### ISSUE THREAD

**Issue by hpompom** [emilsjoerup/DriftBurstHypothesis#5]
Thank you for the effort in building the codes.
The codes are composed of only functions, is there any main script that run all the codes as in the mentioned paper?
Thank you.

**Comment by emilsjoerup** [comment]
Hello @hpompom,

I am sorry for the late answer, unfortunately, I had this repository as unwatched for some reason.

I am not the author of the paper, just a student of Kim's. 
You should send the authors an e-mail, but beware the data used in the paper may be proprietary.

If you need help with using the functions, simulating data or making your own data comply with the rather strict requirements I have made, feel free to reach out.

**Comment by hpompom** [comment]
Thank you for your reply!
